title: WEBAK HOBETO EGITEKO MODUAK. Web bat ahalik eta modu osatuenean sortzeko ideia batzuk!
author: amaiaresende
email: amaia.resende@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
 Kaixo, ongietorriak izan gure lekura! Edozein duda badaukazu, jarri gurekin kontaktuan!
theme: minima